// Generated by Skyramp v1.3.11 on 2026-03-05 16:11:44.846077169 +0000 UTC m=+224.100048280
// Command: skyramp generate contract rest http://localhost:3000/api/categories \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output categories_GET_contract_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// contract test for /api/categories GET
test('testCategoriesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const categoriesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/categories",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(categoriesGetResponse, "20x"), 'status code').toBeTruthy();
});
