// Generated by Skyramp v1.3.11 on 2026-03-05 16:11:44.740388496 +0000 UTC m=+223.994359587
// Command: skyramp generate load rest \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_product_flow_load_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/order-product-flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue } from '@skyramp/skyramp';
import { AsyncScenario, LoadTestConfig } from '@skyramp/skyramp';
// URL for test requests
let URL_accounts = "https://accounts.google.com";
let URL_clients2 = "http://clients2.google.com";
let URL_localhost = "http://localhost:3000";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testLoad', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declare Scenario
    const scenario = new AsyncScenario({name: "scenario"});
    // Declaration of variables
    scenario.setAsyncVar("cart", "true")
    scenario.setAsyncVar("depth", "2")
    scenario.setAsyncVar("gallery", "true")
    scenario.setAsyncVar("gpsia", "1")
    scenario.setAsyncVar("id", "true")
    scenario.setAsyncVar("inventory", "true")
    scenario.setAsyncVar("items", "true")
    scenario.setAsyncVar("options", "true")
    scenario.setAsyncVar("priceInUSD", "true")
    scenario.setAsyncVar("slug", "true")
    scenario.setAsyncVar("subtotal", "true")
    scenario.setAsyncVar("title", "true")

    // Add async request to scenario
    let listAccountsPostResponse = scenario.addAsyncRequest({
        name: "ListAccounts_POST",
        url: URL_accounts,
        path: "/ListAccounts",
        method: "POST",
        queryParams: {
            "gpsia": scenario.getAsyncVar("gpsia"),
            "json": ["standard"],
            "laf": ["b64bin"],
            "source": ["ChromiumBrowser"]
        },
        formParams: {" ": ""},
        expectedCode: "200"
    });



    // Add async request to scenario
    let shopsGetResponse = scenario.addAsyncRequest({
        name: "shops_GET",
        url: URL_localhost,
        path: "/shops",
        method: "GET",
        expectedCode: "404"
    });



    // Add async request to scenario
    let shopsGet1Response = scenario.addAsyncRequest({
        name: "shops_GET_1",
        url: URL_localhost,
        path: "/shops",
        method: "GET",
        expectedCode: "404"
    });



    // Add async request to scenario
    let meGetResponse = scenario.addAsyncRequest({
        name: "me_GET",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet1Response = scenario.addAsyncRequest({
        name: "me_GET_1",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        queryParams: {
            "depth": scenario.getAsyncVar("depth"),
            "select[cart]": ["true"],
            "select[id]": ["true"]
        },
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet2Response = scenario.addAsyncRequest({
        name: "me_GET_2",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        expectedCode: "200"
    });



    // Add async request to scenario
    let faviconIcoGetResponse = scenario.addAsyncRequest({
        name: "favicon_ico_GET",
        url: URL_localhost,
        path: "/favicon.ico",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        expectedCode: "404"
    });



    // Add async request to scenario
    let faviconSvgGetResponse = scenario.addAsyncRequest({
        name: "favicon_svg_GET",
        url: URL_localhost,
        path: "/favicon.svg",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        expectedCode: "404"
    });



    // Add async request to scenario
    let faviconIcoGet1Response = scenario.addAsyncRequest({
        name: "favicon_ico_GET_1",
        url: URL_localhost,
        path: "/favicon.ico",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shops"},
        expectedCode: "404"
    });



    // Add async request to scenario
    let shopGetResponse = scenario.addAsyncRequest({
        name: "shop_GET",
        url: URL_localhost,
        path: "/shop",
        method: "GET",
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet3Response = scenario.addAsyncRequest({
        name: "me_GET_3",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shop"},
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet4Response = scenario.addAsyncRequest({
        name: "me_GET_4",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shop"},
        queryParams: {
            "depth": scenario.getAsyncVar("depth"),
            "select[cart]": ["true"],
            "select[id]": ["true"]
        },
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet5Response = scenario.addAsyncRequest({
        name: "me_GET_5",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shop"},
        expectedCode: "200"
    });



    // Request Body
    const cartsPostRequestBody = `{
            "currency": "USD",
            "items": [
                {
                    "product": 11,
                    "quantity": 1
                }
            ]
        }`
    
    // Add async request to scenario
    let cartsPostResponse = scenario.addAsyncRequest({
        name: "carts_POST",
        url: URL_localhost,
        path: "/api/carts",
        method: "POST",
        body: cartsPostRequestBody,
        headers: {"Referer": "http://localhost:3000/products/airpods"},
        queryParams: {
            "depth": scenario.getAsyncVar("depth"),
            "populate[products][gallery]": ["true"],
            "populate[products][inventory]": ["true"],
            "populate[products][priceInUSD]": ["true"],
            "populate[products][slug]": ["true"],
            "populate[products][title]": ["true"],
            "populate[variants][inventory]": ["true"],
            "populate[variants][options]": ["true"],
            "populate[variants][priceInUSD]": ["true"],
            "populate[variants][title]": ["true"],
            "select[items]": ["true"],
            "select[subtotal]": scenario.getAsyncVar("subtotal")
        },
        dataOverride: {"items.0.quantity": scenario.getAsyncVar("gpsia")},
        expectedCode: "201"
    });



    // Request Body
    const addItemPostRequestBody = `{
            "item": {
                "product": 16
            },
            "quantity": 1,
            "secret": "3480cff71c4102dc628de96ce2c18f9bcc56bd2b"
        }`
    
    // Add async request to scenario
    let addItemPostResponse = scenario.addAsyncRequest({
        name: "add_item_POST",
        url: URL_localhost,
        path: "/api/carts/{carts}/add-item",
        method: "POST",
        body: addItemPostRequestBody,
        headers: {"Referer": "http://localhost:3000/products/hoodie"},
        pathParams: {"carts": cartsPostResponse.getAsyncRequestValue("doc['id']")},
        dataOverride: {
            "quantity": scenario.getAsyncVar("gpsia"),
            "secret": cartsPostResponse.getAsyncRequestValue("doc['secret']")
        },
        expectedCode: "200"
    });



    // Add async request to scenario
    let cartsCartsGetResponse = scenario.addAsyncRequest({
        name: "carts_carts_GET",
        url: URL_localhost,
        path: "/api/carts/{carts}",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/products/hoodie"},
        pathParams: {"carts": cartsPostResponse.getAsyncRequestValue("doc['id']")},
        queryParams: {
            "depth": scenario.getAsyncVar("depth"),
            "populate[products][gallery]": ["true"],
            "populate[products][inventory]": ["true"],
            "populate[products][priceInUSD]": ["true"],
            "populate[products][slug]": ["true"],
            "populate[products][title]": ["true"],
            "populate[variants][inventory]": ["true"],
            "populate[variants][options]": ["true"],
            "populate[variants][priceInUSD]": ["true"],
            "populate[variants][title]": ["true"],
            "secret": cartsPostResponse.getAsyncRequestValue("doc['secret']"),
            "select[items]": ["true"],
            "select[subtotal]": scenario.getAsyncVar("subtotal")
        },
        expectedCode: "200"
    });


    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

