// Generated by Skyramp v1.3.11 on 2026-03-04 23:26:42.411344837 +0000 UTC m=+153.134311224
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_product_flow_integration_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/order-product-flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_accounts = "https://accounts.google.com";
let URL_clients2 = "http://clients2.google.com";
let URL_localhost = "http://localhost:3000";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let cart = "true";
    let depth = "2";
    let gallery = "true";
    let gpsia = "1";
    let id = "true";
    let inventory = "true";
    let items = "true";
    let options = "true";
    let priceInUSD = "true";
    let slug = "true";
    let subtotal = "true";
    let title = "true";

    // Execute Request
    let listAccountsPostResponse = await client.sendRequest({
        url:URL_accounts,
        path:"/ListAccounts",
        method:"POST",
        queryParams:{
            "gpsia": gpsia,
            "json": ["standard"],
            "laf": ["b64bin"],
            "source": ["ChromiumBrowser"]
        },
        formParams:{" ": ""}
    });

    // Generated Assertions
    expect(listAccountsPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let shopsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/shops",
        method:"GET"
    });

    // Generated Assertions
    expect(shopsGetResponse.statusCode, 'status code').toBe(404);

    // Execute Request
    let shopsGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/shops",
        method:"GET"
    });

    // Generated Assertions
    expect(shopsGet1Response.statusCode, 'status code').toBe(404);

    // Execute Request
    let meGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"}
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"},
        queryParams:{
            "depth": depth,
            "select[cart]": ["true"],
            "select[id]": ["true"]
        }
    });

    // Generated Assertions
    expect(meGet1Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet2Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"}
    });

    // Generated Assertions
    expect(meGet2Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let faviconIcoGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"}
    });

    // Generated Assertions
    expect(faviconIcoGetResponse.statusCode, 'status code').toBe(404);

    // Execute Request
    let faviconSvgGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.svg",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"}
    });

    // Generated Assertions
    expect(faviconSvgGetResponse.statusCode, 'status code').toBe(404);

    // Execute Request
    let faviconIcoGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shops"}
    });

    // Generated Assertions
    expect(faviconIcoGet1Response.statusCode, 'status code').toBe(404);

    // Execute Request
    let shopGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/shop",
        method:"GET"
    });

    // Generated Assertions
    expect(shopGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet3Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shop"}
    });

    // Generated Assertions
    expect(meGet3Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet4Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shop"},
        queryParams:{
            "depth": depth,
            "select[cart]": ["true"],
            "select[id]": ["true"]
        }
    });

    // Generated Assertions
    expect(meGet4Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet5Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shop"}
    });

    // Generated Assertions
    expect(meGet5Response.statusCode, 'status code').toBe(200);

    // Request Body
    const cartsPostRequestBody = `{
            "currency": "USD",
            "items": [
                {
                    "product": 11,
                    "quantity": 1
                }
            ]
        }`
    
    // Execute Request
    let cartsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/carts",
        method:"POST",
        body:cartsPostRequestBody,
        headers:{"Referer": "http://localhost:3000/products/airpods"},
        queryParams:{
            "depth": depth,
            "populate[products][gallery]": ["true"],
            "populate[products][inventory]": ["true"],
            "populate[products][priceInUSD]": ["true"],
            "populate[products][slug]": ["true"],
            "populate[products][title]": ["true"],
            "populate[variants][inventory]": ["true"],
            "populate[variants][options]": ["true"],
            "populate[variants][priceInUSD]": ["true"],
            "populate[variants][title]": ["true"],
            "select[items]": ["true"],
            "select[subtotal]": subtotal
        },
        dataOverride:{"items.0.quantity": gpsia}
    });

    // Generated Assertions
    expect(cartsPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const addItemPostRequestBody = `{
            "item": {
                "product": 16
            },
            "quantity": 1,
            "secret": "3480cff71c4102dc628de96ce2c18f9bcc56bd2b"
        }`
    
    // Execute Request
    let addItemPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/carts/{carts}/add-item",
        method:"POST",
        body:addItemPostRequestBody,
        headers:{"Referer": "http://localhost:3000/products/hoodie"},
        pathParams:{"carts": getResponseValue(cartsPostResponse, "doc.id")},
        dataOverride:{
            "quantity": gpsia,
            "secret": getResponseValue(cartsPostResponse, "doc.secret")
        }
    });

    // Generated Assertions
    expect(addItemPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let cartsCartsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/carts/{carts}",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/products/hoodie"},
        pathParams:{"carts": getResponseValue(cartsPostResponse, "doc.id")},
        queryParams:{
            "depth": depth,
            "populate[products][gallery]": ["true"],
            "populate[products][inventory]": ["true"],
            "populate[products][priceInUSD]": ["true"],
            "populate[products][slug]": ["true"],
            "populate[products][title]": ["true"],
            "populate[variants][inventory]": ["true"],
            "populate[variants][options]": ["true"],
            "populate[variants][priceInUSD]": ["true"],
            "populate[variants][title]": ["true"],
            "secret": getResponseValue(cartsPostResponse, "doc.secret"),
            "select[items]": ["true"],
            "select[subtotal]": subtotal
        }
    });

    // Generated Assertions
    expect(cartsCartsGetResponse.statusCode, 'status code').toBe(200);
});

