// Generated by Skyramp v1.3.11 on 2026-03-04 23:26:04.601077709 +0000 UTC m=+115.324044097
// Command: skyramp generate e2e rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_product_flow_e2e_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/my-payload-app/my-payload-app/tests/order-product-flow.zip \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/order-product-flow.json

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testE2E', async ({ page }) => {
    test.setTimeout(239000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:3000/shop");
    await page.getByRole("link", { name: "AirPods AirPods $" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/carts**");
    await page.getByRole("button", { name: "Add to cart" }).click();
    const response0 = await responsePromise0;

    await page.getByRole("link", { name: "All products" }).click();
    await page.getByRole("link", { name: "Hoodie Hoodie $" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/carts/**/add-item**");
    await page.getByRole("button", { name: "Add to cart" }).click();
    const response1 = await responsePromise1;

    await page.getByRole("button", { name: "Cart •" }).click();
    await expect(page.getByText("AirPods$")).toBeVisible();
    await page.getByRole("link", { name: "Proceed to Checkout" }).click();
    await page.getByRole("textbox", { name: "Email Address" }).click();
    await page.getByRole("textbox", { name: "Email Address" }).fill("nk@gmail.com");
    await page.getByRole("button", { name: "Continue as guest" }).click();
    await page.getByRole("button", { name: "Add a new address" }).click();
    await page.getByRole("textbox", { name: "First name*" }).click();
    await page.getByRole("textbox", { name: "First name*" }).fill("N");
    await page.getByRole("textbox", { name: "Last name*" }).click();
    await page.getByRole("textbox", { name: "Last name*" }).fill("K");
    await page.getByRole("textbox", { name: "Phone" }).click();
    await page.getByRole("textbox", { name: "Phone" }).fill("4084429576");
    await page.getByRole("textbox", { name: "Company" }).click();
    await page.getByRole("textbox", { name: "Company" }).fill("Skyramp");
    await page.getByRole("textbox", { name: "Address line 1*" }).click();
    await page.getByRole("textbox", { name: "Address line 1*" }).fill("123 Skyramp Ave");
    await page.getByRole("textbox", { name: "City*" }).click();
    await page.getByRole("textbox", { name: "City*" }).fill("NY");
    await page.getByRole("textbox", { name: "State" }).click();
    await page.getByRole("textbox", { name: "State" }).fill("NY");
    await page.getByRole("textbox", { name: "Zip Code*" }).click();
    await page.getByRole("textbox", { name: "Zip Code*" }).fill("11111");
    await page.getByRole("combobox", { name: "Country*" }).click();
    await page.getByRole("option", { name: "United States" }).click();
    await page.getByRole("button", { name: "Submit" }).click();
    await page.getByRole("button", { name: "Place order" }).click();
});
