// Generated by Skyramp v1.3.11 on 2026-03-04 23:26:13.560073468 +0000 UTC m=+124.283039876
// Reviewed 2026-03-05: Compatible with PostgreSQL migration (db-postgres) and Vercel Blob storage.
// UI flows, routes, and API endpoints are unchanged by the backend infrastructure migration.
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_product_flow_ui_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/my-payload-app/my-payload-app/tests/order-product-flow.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

async function addFirstProductToCart(page) {
    await page.getByRole("link", { name: "AirPods AirPods $" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/carts**");
    await page.getByRole("button", { name: "Add to cart" }).click();
    const response0 = await responsePromise0;
}

async function addSecondProductToCart(page) {
    await page.getByRole("link", { name: "All products" }).click();
    await page.getByRole("link", { name: "Hoodie Hoodie $" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/carts/**/add-item**");
    await page.getByRole("button", { name: "Add to cart" }).click();
    const response1 = await responsePromise1;
}

async function fillShippingAddress(page, firstName, lastName, phone, company, address, city, state, zip) {
    await page.getByRole("button", { name: "Add a new address" }).click();
    await page.getByRole("textbox", { name: "First name*" }).click();
    await page.getByRole("textbox", { name: "First name*" }).fill(firstName);
    await page.getByRole("textbox", { name: "Last name*" }).click();
    await page.getByRole("textbox", { name: "Last name*" }).fill(lastName);
    await page.getByRole("textbox", { name: "Phone" }).click();
    await page.getByRole("textbox", { name: "Phone" }).fill(phone);
    await page.getByRole("textbox", { name: "Company" }).click();
    await page.getByRole("textbox", { name: "Company" }).fill(company);
    await page.getByRole("textbox", { name: "Address line 1*" }).click();
    await page.getByRole("textbox", { name: "Address line 1*" }).fill(address);
    await page.getByRole("textbox", { name: "City*" }).click();
    await page.getByRole("textbox", { name: "City*" }).fill(city);
    await page.getByRole("textbox", { name: "State" }).click();
    await page.getByRole("textbox", { name: "State" }).fill(state);
    await page.getByRole("textbox", { name: "Zip Code*" }).click();
    await page.getByRole("textbox", { name: "Zip Code*" }).fill(zip);
    await page.getByRole("combobox", { name: "Country*" }).click();
    await page.getByRole("option", { name: "United States" }).click();
    await page.getByRole("button", { name: "Submit" }).click();
}

test('testUi', async ({ page }) => {
    test.setTimeout(239000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:3000/shop");
    await addFirstProductToCart(page);
    await addSecondProductToCart(page);

    await page.getByRole("button", { name: "Cart •" }).click();
    await expect(page.getByText("AirPods$")).toBeVisible();
    await page.getByRole("link", { name: "Proceed to Checkout" }).click();
    await page.getByRole("textbox", { name: "Email Address" }).click();
    await page.getByRole("textbox", { name: "Email Address" }).fill("nk@gmail.com");
    await page.getByRole("button", { name: "Continue as guest" }).click();
    await fillShippingAddress(page, "N", "K", "4084429576", "Skyramp", "123 Skyramp Ave", "NY", "NY", "11111");
    await page.getByRole("button", { name: "Place order" }).click();
});
