// Generated by Skyramp v1.3.11 on 2026-03-04 22:25:01.349227412 +0000 UTC m=+121.323747012
// Command: skyramp generate load rest http://localhost:3000/api/reviews \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--query-params productId=1 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode } from '@skyramp/skyramp';
import { AsyncScenario, LoadTestConfig } from '@skyramp/skyramp';
// URL for test requests
let URL = "http://localhost:3000";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testReviewsGet', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Add Request to Scenario
    let reviewsGetResponse = scenario.addAsyncRequest({
        name: "reviews_GET",
        url: URL,
        path: "/api/reviews",
        method: "GET",
        headers: headers,
        queryParams: {"productId": "1"},
        expectedCode: "20x"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

