// Generated by Skyramp v1.3.11 on 2026-03-04 22:24:57.992749592 +0000 UTC m=+117.967269192
// Command: skyramp generate fuzz rest http://localhost:3000/api/reviews \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--request-data {"productId":1,"name":"Test User","email":"test@example.com","rating":5,"body":"Great product!"} \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// fuzz test for /api/reviews POST
test('testReviewsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const reviewsPostRequestBody = `{
            "productId": 1,
            "name": "Test User",
            "email": "test@example.com",
            "rating": 5,
            "body": "Great product!"
        }`
    
    // Fuzz strategies
    const reviewsPostFuzzedBody = {
        "body": "0123456789",
        "email": "0123456789",
        "name": "0123456789",
        "productId": -10,
        "rating": -10
    };
    // Fuzz status codes
    const expectedReviewsPostStatusCode: Record<string, string> = {
        "body": "400",
        "email": "400",
        "name": "400",
        "productId": "400",
        "rating": "400"
    };
    // Fuzz status codes for Null values
    const expectedReviewsPostNullStatusCode: Record<string, string> = {
        "body": "400",
        "email": "400",
        "name": "400",
        "productId": "400",
        "rating": "400"
    };

    // Execute Request
    let reviewsPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/reviews",
        method:"POST",
        body:reviewsPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(reviewsPostFuzzedBody)) {
        // Execute Request
        reviewsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/reviews",
            method:"POST",
            body:reviewsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(reviewsPostFuzzedBody, key)},
            expectedCode:getValue(expectedReviewsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(reviewsPostFuzzedBody, key)}`
        });


        // Execute Request
        reviewsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/reviews",
            method:"POST",
            body:reviewsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedReviewsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

