// Generated by Skyramp v1.3.11 on 2026-03-05 16:11:44.310722791 +0000 UTC m=+223.564693872
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output reviews_flow_integration_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/reviews-flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_accounts = "https://accounts.google.com";
let URL_clients2 = "http://clients2.google.com";
let URL_localhost = "http://localhost:3000";

test('testIntegration', async () => {
    test.setTimeout(65000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let listAccountsPostResponse = await client.sendRequest({
        url:URL_accounts,
        path:"/ListAccounts",
        method:"POST",
        queryParams:{
            "gpsia": ["1"],
            "json": ["standard"],
            "laf": ["b64bin"],
            "source": ["ChromiumBrowser"]
        },
        formParams:{" ": ""}
    });

    // Generated Assertions
    expect(listAccountsPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let endpoint1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/",
        method:"GET"
    });

    // Generated Assertions
    expect(endpoint1GetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let endpoint1Get1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/",
        method:"GET"
    });

    // Generated Assertions
    expect(endpoint1Get1Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/"},
        queryParams:{
            "depth": ["0"],
            "select[cart]": ["true"],
            "select[id]": ["true"]
        }
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/"}
    });

    // Generated Assertions
    expect(meGet1Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let meGet2Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/me",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/"}
    });

    // Generated Assertions
    expect(meGet2Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let faviconSvgGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.svg",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/"}
    });

    // Generated Assertions
    expect(faviconSvgGetResponse.statusCode, 'status code').toBe(500);

    // Execute Request
    let faviconIcoGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/"}
    });

    // Generated Assertions
    expect(faviconIcoGetResponse.statusCode, 'status code').toBe(404);

    // Execute Request
    let faviconSvgGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/favicon.svg",
        method:"GET",
        headers:{"Referer": "http://localhost:3000/shop"}
    });

    // Generated Assertions
    expect(faviconSvgGet1Response.statusCode, 'status code').toBe(404);

    // Request Body
    const reviewsPostRequestBody = `{
            "body": "Amazing products",
            "email": "nk@gmail.com",
            "name": "NK",
            "productId": 11,
            "rating": 5
        }`
    
    // Execute Request
    let reviewsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/reviews",
        method:"POST",
        body:reviewsPostRequestBody,
        headers:{"Referer": "http://localhost:3000/products/airpods"}
    });

    // Generated Assertions
    expect(reviewsPostResponse.statusCode, 'status code').toBe(201);
});

