// Generated by Skyramp v1.3.11 on 2026-03-04 23:26:09.823325984 +0000 UTC m=+120.546292382
// Command: skyramp generate e2e rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output reviews_flow_e2e_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/my-payload-app/my-payload-app/tests/reviews-flow.zip \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/reviews-flow.json

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testE2E', async ({ page }) => {
    test.setTimeout(130000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:3000/");
    await page.getByRole("link", { name: "Shop" }).click();
    await page.getByRole("link", { name: "AirPods AirPods $" }).click();
    await page.getByRole("button", { name: "Rate 5 stars" }).click();
    await page.getByRole("textbox", { name: "Name" }).click();

    const playwrightRequest0: Record<string, any> = {
        "body": "Amazing products",
        "email": "nk@gmail.com",
        "name": "NK"
    };

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    await page.getByRole("textbox", { name: "Review" }).click();
    await page.getByRole("textbox", { name: "Review" }).fill(getValue(playwrightRequest0, "body"));
    await page.getByRole("button", { name: "Submit review" }).click();
    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/reviews**");
    await page.getByRole("button", { name: "Submit review" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "All products" }).click();
    await page.getByRole("link", { name: "sneakers Classic White" }).click();
    await page.getByRole("link", { name: "All products" }).click();
});
