// Generated by Skyramp v1.3.11 on 2026-03-04 22:24:49.995638472 +0000 UTC m=+109.970158072
// Command: skyramp generate contract rest http://localhost:3000/api/reviews \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--request-data {"productId":1,"name":"Test User","email":"test@example.com","rating":4,"body":"Very good product!"} \
// 		--response-status-code 201 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// contract test for /api/reviews POST
test('testReviewsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const reviewsPostRequestBody: string = `{
        "body": "Very good product!",
        "email": "test@example.com",
        "name": "Test User",
        "productId": 1,
        "rating": 4
    }`;

    // Execute Request
    const reviewsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/reviews",
        method: "POST",
        body: reviewsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(reviewsPostResponse.statusCode, 'status code').toBe(201);
});
