// Generated by Skyramp v1.3.11 on 2026-03-04 23:26:51.64511695 +0000 UTC m=+162.368083338
// Command: skyramp generate load rest \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language typescript \
// 		--output reviews_flow_load_test.spec.ts \
// 		--output-dir /home/runner/work/my-payload-app/my-payload-app/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/my-payload-app/my-payload-app/tests/reviews-flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';
import { AsyncScenario, LoadTestConfig } from '@skyramp/skyramp';
// URL for test requests
let URL_accounts = "https://accounts.google.com";
let URL_clients2 = "http://clients2.google.com";
let URL_localhost = "http://localhost:3000";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testLoad', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declare Scenario
    const scenario = new AsyncScenario({name: "scenario"});
    // Add async request to scenario
    let listAccountsPostResponse = scenario.addAsyncRequest({
        name: "ListAccounts_POST",
        url: URL_accounts,
        path: "/ListAccounts",
        method: "POST",
        queryParams: {
            "gpsia": ["1"],
            "json": ["standard"],
            "laf": ["b64bin"],
            "source": ["ChromiumBrowser"]
        },
        formParams: {" ": ""},
        expectedCode: "200"
    });



    // Add async request to scenario
    let endpoint1GetResponse = scenario.addAsyncRequest({
        name: "endpoint_1_GET",
        url: URL_localhost,
        path: "/",
        method: "GET",
        expectedCode: "200"
    });



    // Add async request to scenario
    let endpoint1Get1Response = scenario.addAsyncRequest({
        name: "endpoint_1_GET_1",
        url: URL_localhost,
        path: "/",
        method: "GET",
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGetResponse = scenario.addAsyncRequest({
        name: "me_GET",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/"},
        queryParams: {
            "depth": ["0"],
            "select[cart]": ["true"],
            "select[id]": ["true"]
        },
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet1Response = scenario.addAsyncRequest({
        name: "me_GET_1",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/"},
        expectedCode: "200"
    });



    // Add async request to scenario
    let meGet2Response = scenario.addAsyncRequest({
        name: "me_GET_2",
        url: URL_localhost,
        path: "/api/users/me",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/"},
        expectedCode: "200"
    });



    // Add async request to scenario
    let faviconSvgGetResponse = scenario.addAsyncRequest({
        name: "favicon_svg_GET",
        url: URL_localhost,
        path: "/favicon.svg",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/"},
        expectedCode: "500"
    });



    // Add async request to scenario
    let faviconIcoGetResponse = scenario.addAsyncRequest({
        name: "favicon_ico_GET",
        url: URL_localhost,
        path: "/favicon.ico",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/"},
        expectedCode: "404"
    });



    // Add async request to scenario
    let faviconSvgGet1Response = scenario.addAsyncRequest({
        name: "favicon_svg_GET_1",
        url: URL_localhost,
        path: "/favicon.svg",
        method: "GET",
        headers: {"Referer": "http://localhost:3000/shop"},
        expectedCode: "404"
    });



    // Request Body
    const reviewsPostRequestBody = `{
            "body": "Amazing products",
            "email": "nk@gmail.com",
            "name": "NK",
            "productId": 11,
            "rating": 5
        }`
    
    // Add async request to scenario
    let reviewsPostResponse = scenario.addAsyncRequest({
        name: "reviews_POST",
        url: URL_localhost,
        path: "/api/reviews",
        method: "POST",
        body: reviewsPostRequestBody,
        headers: {"Referer": "http://localhost:3000/products/airpods"},
        expectedCode: "201"
    });


    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

